### ISSUE TITLE
Need to fix the padding for the infobar

### ISSUE THREAD

**Issue by baconC** [ciena-frost/ember-frost-info-bar#25]

**Comment by rox163** [comment]
Not sure which padding this refers to, so @baconC could you check out  http://ciena-frost.github.io/ember-frost-info-bar/ and note if any changes are required?

**Comment by baconC** [comment]
ah.. thats so long ago, must be fixed with your changes. 

can you add margin-top: -5px; to  .frost-info-bar-icon~.title?
that would be all good after. 

thx

**Comment by sglanzer** [comment]
Needs a re-test

**Comment by pbosse** [comment]
For some reason, the icon on the left is not 10px from the top, closer to 5px, is that what is wanted?
![image](https://user-images.githubusercontent.com/8288485/28836817-79fc4f40-76b8-11e7-8738-c9656b895e9c.png)

**Comment by rox163** [comment]
updates have been made to ember-frost-core for the padding adjustments.
