### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by sglanzer** [ciena-frost/ember-frost-info-bar#29]

**Comment by juwara0** [comment]
I have made some updates to the README in: https://github.com/juwara0/ember-frost-info-bar/blob/00f55b78af04e51d9f8ade0ee66cf8f12379c642/README.md

One thing that needs to still be corrected is to change the actions slot to reflect the flattened icon paths:

```
{{#block-slot 'actions' as |action|}}
    {{action.button icon='frost/infobar-create' text='Click me!' onClick=(action 'triggerAction')}}
  {{/block-slot}}
```

Should be changed to:
```
{{#block-slot 'actions' as |action|}}
    {{action.button icon='infobar-create' text='Click me!' onClick=(action 'triggerAction')}}
  {{/block-slot}}
```

**Comment by rox163** [comment]
README reflects latest implementation
